name: 'Varlock Environment Loader'
description: 'Load and validate environment variables using varlock schema validation'
author: 'dmno-dev'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  working-directory:
    description: 'Directory containing .env.schema files'
    required: false
    default: '.'
  show-summary:
    description: 'Show a summary of loaded environment variables'
    required: false
    default: 'true'
  fail-on-error:
    description: 'Fail the action if validation errors are found'
    required: false
    default: 'true'
  output-format:
    description: 'Output format: "env" exports variables as environment variables/secrets, "json" outputs a single JSON blob'
    required: false
    default: 'env'

outputs:
  summary:
    description: 'Summary of loaded environment variables'
    value: ${{ steps.varlock.outputs.summary }}
  error-count:
    description: 'Number of validation errors found'
    value: ${{ steps.varlock.outputs.error-count }}
  json-env:
    description: 'JSON blob containing all environment variables (only available when output-format is "json"). This will contain all environment variables, including sensitive ones. Be careful.'
    value: ${{ steps.varlock.outputs.json-env }}

runs:
  using: 'node22'
  main: 'dist/index.js' 