name: Example Varlock GitHub Action Usage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-with-varlock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set environment flag
        run: echo "APP_ENV=testing" >> $GITHUB_ENV
      
      - name: Load environment variables with varlock
        uses: dmno-dev/varlock-github-action@v1
      
      - name: Use loaded environment variables
        run: |
          echo "Database URL: $DATABASE_URL"
          echo "API Key: $API_KEY"
          echo "Debug mode: $DEBUG"
          echo "Port: $PORT"
          echo "Node environment: $NODE_ENV"
      
      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test
      
      - name: Build application
        run: npm run build

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test-with-varlock
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set environment flag
        run: echo "APP_ENV=production" >> $GITHUB_ENV
      
      - name: Load production environment variables
        uses: dmno-dev/varlock-github-action@v1
        with:
          working-directory: './config'
          show-summary: 'true'
          fail-on-error: 'true'
          output-format: 'json'
      
      - name: Deploy to production
        run: |
          echo "Deploying to production environment"
          echo "Database: $DATABASE_URL"
          echo "Redis: $REDIS_URL"
          echo "API Key: $API_KEY"
          # Your deployment script here 